services:

  #----------------------PostgreSQL------------------------
  postgresql:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "1234"
    networks:
      - jobSpotter-net
    restart: unless-stopped

  #----------------------MongoDB------------------------
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017"
    volumes:
      - mongodb:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - jobSpotter-net  # Include MongoDB in the network

  #----------------------Kafka and zookeper------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog
    ports:
      - "22181"
    networks:
      - jobSpotter-net



  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - jobSpotter-net


  #----------------------Keycloak------------------------
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    networks:
      - jobSpotter-net

  keycloak:
      image: quay.io/keycloak/keycloak:26.0.0
      container_name: keycloak
      environment:
        KC_DB: postgres
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KC_DB_URL: jdbc:postgresql://keycloak-db/keycloak
        KC_HOSTNAME: keycloak
        KC_BOOTSTRAP_ADMIN_USERNAME: admin
        KC_BOOTSTRAP_ADMIN_PASSWORD: admin
        KC_LOG_LEVEL: info
      command: start-dev --import-realm
      ports:
        - "8080"
      depends_on:
        - keycloak-db
      volumes:
        - keycloak:/opt/keycloak/data
        - ./keycloak/realm-import.json:/opt/keycloak/data/import/realm-import.json:ro
      networks:
        - jobSpotter-net



  #        ----------------------Redis-------------------------

  redis:
    image: redis/redis-stack:latest  #  Use Redis Stack (Includes RediSearch)
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379"
      - "8001"  # RedisInsight UI
    volumes:
      - redis:/data
    networks:
      - jobSpotter-net

  #        --------------------------------------------Tools (Monitoring, Tracing)---------------------------------------------

  #----------------------Zipkin------------------------
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - jobSpotter-net


  #----------------------Prometheus------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_1
    ports:
      - "9091"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - jobSpotter-net
    restart: unless-stopped


  #----------------------Grafana------------------------
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - prometheus
    links:
      - prometheus:prometheus # Link to Prometheus
    networks:
      - jobSpotter-net
    restart: unless-stopped
    volumes:
      - ./grafana:/var/lib/grafana  # Persist Grafana data






  #      ---------------------------------------JOBSPOTTER SERVICES------------------------------------------------

  #----------------------Config Server------------------------
  config-server:
    container_name: config-server
    image: jobspotter/config-server:latest
    networks:
      - jobSpotter-net

  #----------------------Discovery Server (Eureka)------------------------
  discovery:
    container_name: discovery-service
    image: jobspotter/discovery:ad5bfa2dfc1505ecca3634bcbf8a4f3599e46a4d
    networks:
      - jobSpotter-net
    depends_on:
      - config-server

  #----------------------Gateway------------------------
  gateway:
    container_name: gateway
    image: jobspotter/gateway:latest
    ports:
      - "443:443"
    environment:
      - KEYCLOAK_ADMIN_CLIENT_ID=${KEYCLOAK_ADMIN_CLIENT_ID}
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - KEYSTORE_LOCATION=${KEYSTORE_LOCATION}
      - CERTIFICATE_LOCATION=${CERTIFICATE_LOCATION}
      - SSL_ON=true

    volumes:
      - ./certs:/ssl 

    networks:
      - jobSpotter-net
    depends_on:
      - discovery
      - config-server
      - keycloak

  #----------------------Job Post Service------------------------
  job-post:
    container_name: job-post
    image: jobspotter/job-post:879e0dc86e579d5d008bed4f7c2eb8c82119e567
    networks:
      - jobSpotter-net

    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    depends_on:
      - discovery
      - config-server
      - postgresql
      - gateway
      - redis
      - keycloak

  #----------------------Notification Service------------------------
  notification:
    container_name: notification
    image: jobspotter/notification:85ab84fb127638a7e53fc9c087ced23c2f9d5549
    networks:
      - jobSpotter-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker 
    depends_on:
      - discovery
      - config-server
      - gateway
      - mongodb

  #----------------------Report Service------------------------
  report:
    container_name: report
    image:  jobspotter/report:ad5bfa2dfc1505ecca3634bcbf8a4f3599e46a4d
    networks:
      - jobSpotter-net
    environment:
      - KEYCLOAK_HOST_URL=${KEYCLOAK_HOST_URL}
    depends_on:
      - discovery
      - config-server
      - gateway
      - redis
      - keycloak
      - mongodb

  #----------------------Review Service------------------------
  review:
    container_name: review
    image:  jobspotter/review:ad5bfa2dfc1505ecca3634bcbf8a4f3599e46a4d
    networks:
      - jobSpotter-net
    depends_on:
      - discovery
      - config-server
      - gateway
      - redis
      - keycloak
      - postgresql

  #----------------------User Service------------------------
  user:
    container_name: user
    image:  jobspotter/user:009c57b9fa4caefe91b8205eda8dff82fa05e91e
    networks:
      - jobSpotter-net
    environment:
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_ACCESS_KEY_ID=${AWS_S3_ACCESS_KEY_ID}
      - AWS_S3_SECRET_ACCESS_KEY=${AWS_S3_SECRET_ACCESS_KEY}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - KEYCLOAK_ADMIN_CLIENT_ID=${KEYCLOAK_ADMIN_CLIENT_ID}
      - KEYCLOAK_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - GOOGLE_GEOCODING_API_KEY=${GOOGLE_GEOCODING_API_KEY}
      - KEYCLOAK_HOST_URL=${KEYCLOAK_HOST_URL}
    depends_on:
      - discovery
      - config-server
      - gateway
      - postgresql
      - redis
      - keycloak



#        ----------------------Network------------------------

networks:
  jobSpotter-net:
    driver: bridge

volumes:
  postgres:
  mongodb:
  keycloak:
  keycloak_db:
  redis: {}
  zookeeper-data: {}
  zookeeper-datalog: {}
  kafka-data: {}
  grafana: {}
