INSERT INTO tag (tag_id, name) VALUES
                                   (1, 'General Help'),
                                   (2, 'Handyman Services'),
                                   (3, 'Skilled Trades'),
                                   (4, 'Cleaning Services'),
                                   (5, 'Delivery Services'),
                                   (6, 'Caregiving'),
                                   (7, 'Pet Care'),
                                   (8, 'Tutoring/Mentoring'),
                                   (9, 'Event Staff'),
                                   (10, 'Administrative Support'),
                                   (11, 'Virtual Assistance'),
                                   (12, 'Food Services'),
                                   (13, 'Gardening/Landscaping'),
                                   (14, 'Community Outreach'),
                                   (15, 'IT Support'),
                                   (16, 'Creative Services'),
                                   (17, 'Personal Services'),
                                   (18, 'Tutoring Languages'),
                                   (19, 'Music Instruction'),
                                   (20, 'Home Maintenance'),
                                   (21, 'Transportation Assistance'),
                                   (22, 'Errands/Shopping'),
                                   (23, 'Volunteer Work'),
                                   (24, 'Community Events'),
                                   (25, 'Fundraising'),
                                   (26, 'Animal Welfare'),
                                   (27, 'Mentoring (Community)'),
                                   (28, 'Health Support'),
                                   (29, 'Counseling Support'),
                                   (30, 'Disaster Relief'),
                                   (31, 'Environmental Conservation'),
                                   (32, 'Other');
