
services:
  jobspotter-frontend:
    image: jobspotter/jobspotter-frontend:latest
    container_name: jobspotter-frontend
    ports:
      - "80:80"
    networks:
      - default
    environment:
      - VITE_API_URL=http://host.docker.internal:8100
