services:
  jobspotter-frontend:
    image: jobspotter/jobspotter-frontend:latest
    container_name: jobspotter-frontend
    ports:
      - "80:80"
    networks:
      - jobspotterserver_jobSpotter-net

networks:
  jobspotterserver_jobSpotter-net:
    external: true
